#!/usr/bin/env python3
"""Regenerate the JSON Schema validators under research/schemas/ from the knowledge file.

Each schema is a mechanical projection of the knowledge JSON (issue #4):
settings from `config_keys`, hooks from `extensibility.hooks`, mcp-config from
`extensibility.mcp`, and agent frontmatter from `extensibility.agents.frontmatter`.
Run this after the knowledge file changes; `check_consistency.py` cross-checks
the checked-in schemas against the knowledge file in CI either way, and
`--check` compares the full files byte-for-byte.

Usage:
    python3 research/scripts/gen_schemas.py           # regenerate all four schemas
    python3 research/scripts/gen_schemas.py --check   # compare without writing

Exit codes:
    0  schemas match the generator output (--check) or were regenerated
    1  drift found (--check) or a required container is missing
"""

import argparse
import json
import sys

from paths import knowledge_json, schemas_dir

DRAFT = "http://json-schema.org/draft-07/schema#"


def dump(schema: dict) -> str:
    """Serialize a schema deterministically (sorted keys, 2-space indent)."""
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def _json_type(kind: str) -> dict:
    """Map the knowledge file's type vocabulary to a JSON Schema type fragment."""
    if kind == "boolean":
        return {"type": "boolean"}
    if kind == "number":
        return {"type": "number"}
    if kind == "array":
        return {"type": "array", "items": {"type": "string"}}
    if kind == "string[]":
        return {"type": "array", "items": {"type": "string"}}
    if kind == "object[]":
        return {"type": "array", "items": {"type": "object"}}
    if kind == "object":
        return {"type": "object", "additionalProperties": True}
    return {"type": "string"}


def _config_key_schema(entry: dict) -> dict:
    """One settings key schema: type + enum + default from its config_keys entry."""
    schema = _json_type(entry.get("type", "string"))
    if entry.get("enum"):
        schema["enum"] = entry["enum"]
    if "default" in entry:
        schema["default"] = entry["default"]
    return schema


def build_settings(data: dict) -> dict:
    """settings.schema.json: nested projection of the documented config_keys."""
    properties: dict = {}
    for entry in data["config_keys"]["entries"]:
        key = entry.get("key")
        if not key:
            continue
        node = properties
        parts = key.split(".")
        for i, part in enumerate(parts):
            if i == len(parts) - 1:
                node[part] = _config_key_schema(entry)
            else:
                node = node.setdefault(
                    part,
                    {"type": "object", "properties": {}, "additionalProperties": True},
                )["properties"]
    return {
        "$schema": DRAFT,
        "$id": "settings.schema.json",
        "title": "Antigravity CLI settings.json",
        "description": (
            "Projection of the documented config_keys in the knowledge file "
            "(research/schema/antigravity-cli-knowledge.json). Regenerated by "
            "gen_schemas.py; cross-checked by check_consistency.py. Unknown keys "
            "are allowed: the knowledge base is deliberately permissive about "
            "undocumented keys."
        ),
        "type": "object",
        "properties": properties,
        "additionalProperties": True,
    }


def build_hooks(data: dict) -> dict:
    """hooks.schema.json: hook-group mapping with the documented events."""
    fields = data["extensibility"]["hooks"].get("definition_fields", [])
    group_properties: dict = {}
    for f in fields:
        name = f.get("field")
        if not name:
            continue
        if name == "enabled":
            group_properties["enabled"] = {"type": "boolean", "default": True}
        else:
            group_properties[name] = {"$ref": "#/definitions/matcherList"}
        if f.get("description"):
            group_properties[name]["description"] = f["description"]
    return {
        "$schema": DRAFT,
        "$id": "hooks.schema.json",
        "title": "Antigravity CLI hooks.json",
        "description": (
            "Projection of the documented hook surface (extensibility.hooks in "
            "the knowledge file). Root is a mapping of hook-group names; each "
            "group carries the documented event arrays. Unknown group keys are "
            "allowed (community aliases like AfterToolUse are unresolved)."
        ),
        "type": "object",
        "additionalProperties": {"$ref": "#/definitions/hookGroup"},
        "definitions": {
            "hookGroup": {
                "type": "object",
                "properties": group_properties,
                "additionalProperties": True,
            },
            "matcherList": {
                "type": "array",
                "items": {"$ref": "#/definitions/matcherEntry"},
            },
            "matcherEntry": {
                "type": "object",
                "properties": {
                    "matcher": {
                        "type": "string",
                        "description": (
                            'Tool matcher: "" or "*" matches all, '
                            '"run_command" exact, "run_command|view_file" '
                            'either, "browser_.*" regex prefix'
                        ),
                    },
                    "hooks": {
                        "type": "array",
                        "items": {"$ref": "#/definitions/hookEntry"},
                    },
                },
                "additionalProperties": True,
            },
            "hookEntry": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": 'Hook type, e.g. "command"',
                    },
                    "command": {
                        "type": "string",
                        "description": (
                            "Script to run; receives JSON on stdin, emits JSON "
                            "on stdout"
                        ),
                    },
                    "timeout": {
                        "type": "number",
                        "description": (
                            "Timeout in seconds; non-zero exit from PreToolUse "
                            "cancels execution"
                        ),
                    },
                },
                "additionalProperties": True,
            },
        },
    }


def build_mcp(data: dict) -> dict:
    """mcp-config.schema.json: transport props, oneOf gate, and legacy rejection."""
    mcp = data["extensibility"]["mcp"]
    properties: dict = {}
    for spec in [*mcp.get("transport", []), *mcp.get("optional_properties", [])]:
        name = spec.get("property")
        if not name:
            continue
        properties[name] = _json_type(spec.get("type", "string"))
        if spec.get("description"):
            properties[name]["description"] = spec["description"]
    properties["url"] = False
    properties["httpUrl"] = False
    return {
        "$schema": DRAFT,
        "$id": "mcp-config.schema.json",
        "title": "Antigravity CLI mcp_config.json",
        "description": (
            "Projection of the documented MCP server surface "
            "(extensibility.mcp in the knowledge file). Legacy url/httpUrl "
            "fields are rejected: Antigravity CLI requires serverUrl. A server "
            "must configure exactly one transport: command (Stdio) or serverUrl "
            "(Remote)."
        ),
        "type": "object",
        "required": ["mcpServers"],
        "properties": {
            "mcpServers": {
                "type": "object",
                "description": "Server name -> server configuration",
                "additionalProperties": {"$ref": "#/definitions/server"},
            }
        },
        "additionalProperties": True,
        "definitions": {
            "server": {
                "type": "object",
                "properties": properties,
                "oneOf": [{"required": ["command"]}, {"required": ["serverUrl"]}],
                "additionalProperties": True,
            }
        },
    }


def build_agent(data: dict) -> dict:
    """agent-frontmatter.schema.json: frontmatter fields with the tools enum."""
    fields = data["extensibility"]["agents"]["frontmatter"]
    tools = sorted(e["name"] for e in data["tools"]["entries"])
    properties: dict = {}
    required: list[str] = []
    for f in fields:
        name = f.get("field")
        if not name:
            continue
        if f.get("default") == "required":
            required.append(name)
        if name == "skills / plugins":
            properties["skills"] = {"type": "array", "items": {"type": "string"}}
            properties["plugins"] = {"type": "array", "items": {"type": "string"}}
            continue
        if name == "tools":
            schema = {
                "type": "array",
                "items": {"type": "string", "enum": tools},
            }
        else:
            schema = _json_type(f.get("type", "string"))
            if f.get("enum"):
                schema["enum"] = f["enum"]
        if f.get("description"):
            schema["description"] = f["description"]
        if f.get("default") and f["default"] != "required":
            schema["default"] = f["default"]
        properties[name] = schema
    return {
        "$schema": DRAFT,
        "$id": "agent-frontmatter.schema.json",
        "title": "Antigravity CLI agent YAML frontmatter",
        "description": (
            "Projection of the documented agent frontmatter fields "
            "(extensibility.agents.frontmatter in the knowledge file). The tools "
            "enum is cross-checked against the documented tool set by "
            "check_consistency.py so misspelled tool names (a documented cause "
            "of subagent hangs) are caught."
        ),
        "type": "object",
        "required": required,
        "properties": properties,
        "additionalProperties": True,
    }


def build_all(data: dict) -> dict[str, dict]:
    """Return {filename: schema} for every config surface."""
    return {
        "settings.schema.json": build_settings(data),
        "hooks.schema.json": build_hooks(data),
        "mcp-config.schema.json": build_mcp(data),
        "agent-frontmatter.schema.json": build_agent(data),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="compare checked-in schemas against generator output without writing",
    )
    args = ap.parse_args()

    try:
        data = json.loads(knowledge_json().read_text(encoding="utf-8"))
    except OSError as e:
        print(f"FAIL  cannot read knowledge file: {e}")
        return 1

    generated = build_all(data)

    if args.check:
        drift = []
        for name, schema in generated.items():
            path = schemas_dir() / name
            if not path.exists():
                drift.append(f"{name}: missing (expected generator output)")
            elif path.read_text(encoding="utf-8") != dump(schema):
                drift.append(f"{name}: differs from generator output")
        if drift:
            print(f"FAIL  schema drift: {'; '.join(drift)}")
            return 1
        print("ok    checked-in schemas match generator output")
        return 0

    for name, schema in generated.items():
        (schemas_dir() / name).write_text(dump(schema), encoding="utf-8")
    print(f"regenerated {len(generated)} schema(s) under {schemas_dir()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
